version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:13-alpine
    container_name: joineazy_db_dev
    environment:
      - POSTGRES_DB=joineazy_feedback
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: joineazy_server_dev
    environment:
      - NODE_ENV=development
      - PORT=5000
      - JWT_SECRET=joineazy_super_secret_key_dev
      - JWT_EXPIRES_IN=7d
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=joineazy_feedback
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: on-failure
    volumes:
      - ./server:/app
      - /app/node_modules
    command: sh -c "npm install -g nodemon && nodemon --legacy-watch src/index.js"

  # Frontend React App
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: joineazy_client_dev
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - WDS_SOCKET_PORT=0
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: on-failure
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true

volumes:
  postgres_data_dev: